CREATE SEQUENCE SEQ_TRASH_CATEGORY
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_GAMES(
    ID INTEGER DEFAULT SEQ_TRASH_CATEGORY.NEXTVAL NOT NULL,
    NAME VARCHAR2(100) NOT NULL
);