CREATE SEQUENCE SEQ_COLLECT_POINT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_COLLECT_POINT (
    ID NUMBER(19,0) DEFAULT SEQ_COLLECT_POINT.NEXTVAL NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    ADDRESS VARCHAR2(255),
    TRASH_TYPE VARCHAR2(100),
    LATITUDE FLOAT(126),
    LONGITUDE FLOAT(126),
    CONSTRAINT PK_TBL_COLLECT_POINT PRIMARY KEY (ID)
);
